"""
Range Engine Configuration

Per-pair parameters and shared constants for the BB+ATR+ADX range calculation engine.
"""

from dataclasses import dataclass
from typing import Dict


# =============================================================================
# Regime Thresholds (ADX-based)
# =============================================================================

# ADX < 25: Ranging market - trade mean-reversion
REGIME_RANGING_ADX_MAX = 25

# ADX 25-30: Caution zone - reduce position size
REGIME_CAUTION_ADX_MIN = 25
REGIME_CAUTION_ADX_MAX = 30

# ADX > 30: Trending market - skip mean-reversion trades
REGIME_TRENDING_ADX_MIN = 30


# =============================================================================
# Entry Thresholds (RSI-based)
# =============================================================================

# RSI below this value confirms oversold condition for entry
RSI_OVERSOLD = 40

# RSI above this value triggers exit (overbought)
RSI_OVERBOUGHT_EXIT = 60


# =============================================================================
# Indicator Periods
# =============================================================================

# Bollinger Bands period
BB_PERIOD = 20

# Standard deviation multiplier for BB
BB_STD_DEV_MULT = 2.0

# ATR period
ATR_PERIOD = 14

# ADX period
ADX_PERIOD = 14

# RSI period
RSI_PERIOD = 14

# ATR multiplier for stop loss
ATR_STOP_MULT = 1.5

# ATR multiplier for trailing exit
ATR_EXIT_MULT = 1.5


# =============================================================================
# Per-Pair Configuration
# =============================================================================

@dataclass
class PairConfig:
    """Configuration for a single trading pair."""
    bb_period: int
    atr_period: int
    adx_period: int
    rsi_period: int
    atr_stop_mult: float
    atr_exit_mult: float
    min_width: float  # Minimum range width as decimal (e.g., 0.015 = 1.5%)
    fee_rate: float   # Fee rate as decimal (e.g., 0.0005 = 0.05%)


# Per-pair configuration dictionary
# Keyed by pair string (e.g., 'WETH/USDC')
PER_PAIR_CONFIG: Dict[str, PairConfig] = {
    'WETH/USDC': PairConfig(
        bb_period=BB_PERIOD,
        atr_period=ATR_PERIOD,
        adx_period=ADX_PERIOD,
        rsi_period=RSI_PERIOD,
        atr_stop_mult=ATR_STOP_MULT,
        atr_exit_mult=ATR_EXIT_MULT,
        min_width=0.015,    # 1.5% minimum width
        fee_rate=0.0005,    # 0.05% fee (slipstream pool)
    ),
    'cbBTC/WETH': PairConfig(
        bb_period=BB_PERIOD,
        atr_period=ATR_PERIOD,
        adx_period=ADX_PERIOD,
        rsi_period=RSI_PERIOD,
        atr_stop_mult=ATR_STOP_MULT,
        atr_exit_mult=ATR_EXIT_MULT,
        min_width=0.015,    # 1.5% minimum width
        fee_rate=0.0005,    # 0.05% fee (slipstream pool)
    ),
    'AERO/USDC': PairConfig(
        bb_period=BB_PERIOD,
        atr_period=ATR_PERIOD,
        adx_period=ADX_PERIOD,
        rsi_period=RSI_PERIOD,
        atr_stop_mult=ATR_STOP_MULT,
        atr_exit_mult=ATR_EXIT_MULT,
        min_width=0.020,    # 2.0% minimum width
        fee_rate=0.003,     # 0.30% fee (standard pool)
    ),
    'ZEN/WETH': PairConfig(
        bb_period=BB_PERIOD,
        atr_period=ATR_PERIOD,
        adx_period=ADX_PERIOD,
        rsi_period=RSI_PERIOD,
        atr_stop_mult=ATR_STOP_MULT,
        atr_exit_mult=ATR_EXIT_MULT,
        min_width=0.030,    # 3.0% minimum width
        fee_rate=0.0015,    # 0.15% fee
    ),
    'VFY/USDC': PairConfig(
        bb_period=BB_PERIOD,
        atr_period=ATR_PERIOD,
        adx_period=ADX_PERIOD,
        rsi_period=RSI_PERIOD,
        atr_stop_mult=ATR_STOP_MULT,
        atr_exit_mult=ATR_EXIT_MULT,
        min_width=0.060,    # 6.0% minimum width
        fee_rate=0.003,     # 0.30% fee (Uniswap v4)
    ),
}


# =============================================================================
# Regime Enum (for type hints and clarity)
# =============================================================================

class Regime:
    """Market regime classifications based on ADX."""
    RANGING = "RANGING"
    CAUTION = "CAUTION"
    TRENDING = "TRENDING"


# =============================================================================
# Signal Types (for type hints and clarity)
# =============================================================================

class Signal:
    """Signal types generated by the range engine."""
    ENTER_LONG = "ENTER_LONG"
    EXIT_LONG = "EXIT_LONG"
    HOLD = "HOLD"
    SKIP = "SKIP"


# =============================================================================
# Entry Thresholds (convenience class)
# =============================================================================

class EntryThresholds:
    """Entry threshold constants."""
    RSI_OVERSOLD = RSI_OVERSOLD
    RSI_OVERBOUGHT_EXIT = RSI_OVERBOUGHT_EXIT
    ADX_RANGING_MAX = REGIME_RANGING_ADX_MAX
    ADX_TRENDING_MIN = REGIME_TRENDING_ADX_MIN
